# Generated by Django 2.2.8 on 2020-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Filelist',
            fields=[
                ('info_hash', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('file_list', models.TextField()),
            ],
            options={
                'db_table': 'search_filelist',
            },
        ),
        migrations.CreateModel(
            name='Search_Hash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info_hash', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('data_hash', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=20)),
                ('classified', models.BooleanField(default=False)),
                ('source_ip', models.CharField(max_length=20)),
                ('tagged', models.BooleanField(default=False)),
                ('length', models.BigIntegerField()),
                ('create_time', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('requests', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'search_hash',
            },
        ),
        migrations.CreateModel(
            name='Search_Keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=20, unique=True)),
                ('order', models.IntegerField()),
                ('pic', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'search_keywords',
            },
        ),
        migrations.CreateModel(
            name='Search_Statusreport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('new_hashes', models.IntegerField()),
                ('total_requests', models.IntegerField()),
                ('valid_requests', models.IntegerField()),
            ],
            options={
                'db_table': 'search_statusreport',
            },
        ),
        migrations.CreateModel(
            name='Search_Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'search_tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
